repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  #  -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        additional_dependencies: ['click==8.0.4']
        exclude: ^dist/
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    - id: isort
