# Generated by Django 3.2.4 on 2021-06-18 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="time",
            field=models.DateTimeField(default="timezone.now"),
        ),
        migrations.AddField(
            model_name="homeworkresult",
            name="time",
            field=models.DateTimeField(default="timezone.now"),
        ),
        migrations.AddField(
            model_name="student",
            name="new_value",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=250, verbose_name="Name"
            ),
            preserve_default=False,
        ),
    ]
